export const menuData = {
    entradas: [
      {
        id: 1,
        nombre: "Ceviche Clásico",
        descripcion: "Pescado fresco del día marinado en limón con cebolla morada, ají limo, camote dulce y cancha serrana. Una explosión de sabores marinos que despierta todos los sentidos.",
        precio: 35.00,
        destacado: true,
        imagen: "../public/images/placeholder-frqdb.png",
        calorias: 280,
        tiempo: "15 min",
        picante: 2,
        rating: 4.8,
        ingredientes: ["Pescado fresco", "Limón", "Cebolla morada", "Ají limo", "Camote", "Cancha"]
      },
      {
        id: 2,
        nombre: "Tiradito de Lenguado",
        descripcion: "Finas láminas de lenguado fresco bañadas en una cremosa salsa de ají amarillo, acompañado de maíz cancha tostado y microgreens.",
        precio: 32.00,
        destacado: false,
        imagen: "../public/images/tiradito-lenguado-aji-amarillo.png",
        calorias: 220,
        tiempo: "12 min",
        picante: 1,
        rating: 4.6,
        ingredientes: ["Lenguado", "Ají amarillo", "Cancha", "Microgreens"]
      },
      {
        id: 3,
        nombre: "Causa Limeña",
        descripcion: "Capas de papa amarilla sazonada con ají amarillo, rellena de pollo deshilachado en salsa golf, palta cremosa y huevo duro.",
        precio: 28.00,
        destacado: false,
        imagen: "../public/images/causa-limena-pollo.png",
        calorias: 350,
        tiempo: "20 min",
        picante: 1,
        rating: 4.5,
        ingredientes: ["Papa amarilla", "Pollo", "Palta", "Huevo", "Salsa golf"]
      },
      {
        id: 4,
        nombre: "Anticuchos de Pulpo",
        descripcion: "Tiernos trozos de pulpo a la parrilla marinados en salsa anticuchera especial, acompañados de papa dorada y choclo.",
        precio: 38.00,
        destacado: true,
        imagen: "../public/images/anticuchos-pulpo-parrilla-peruano.png",
        calorias: 320,
        tiempo: "25 min",
        picante: 2,
        rating: 4.9,
        ingredientes: ["Pulpo", "Salsa anticuchera", "Papa", "Choclo"]
      },
      {
        id: 5,
        nombre: "Palta Rellena",
        descripcion: "Palta fresca rellena con ensalada de camarones, apio, mayonesa casera y un toque de limón. Entrada ligera y refrescante.",
        precio: 26.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 280,
        tiempo: "10 min",
        picante: 0,
        rating: 4.3,
        ingredientes: ["Palta", "Camarones", "Apio", "Mayonesa", "Limón"]
      },
      {
        id: 6,
        nombre: "Choritos a la Chalaca",
        descripcion: "Mejillones frescos con salsa chalaca de cebolla, tomate, ají limo y culantro. Sabor intenso del mar peruano.",
        precio: 24.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 180,
        tiempo: "15 min",
        picante: 2,
        rating: 4.4,
        ingredientes: ["Choritos", "Cebolla", "Tomate", "Ají limo", "Culantro"]
      }
    ],
    principales: [
      {
        id: 7,
        nombre: "Arroz con Mariscos",
        descripcion: "Arroz amarillo cocinado con langostinos, pulpo, calamar, mejillones y conchas negras. Un festival de mariscos frescos en cada cucharada.",
        precio: 45.00,
        destacado: true,
        imagen: "../public/images/arroz-con-mariscos-langostinos-peruano.png",
        calorias: 520,
        tiempo: "35 min",
        picante: 1,
        rating: 4.9,
        ingredientes: ["Arroz", "Langostinos", "Pulpo", "Calamar", "Mejillones", "Conchas negras"]
      },
      {
        id: 8,
        nombre: "Pescado a la Plancha",
        descripcion: "Filete de pescado fresco a la plancha con hierbas aromáticas, acompañado de ensalada fresca y papas doradas.",
        precio: 42.00,
        destacado: false,
        imagen: "../public/images/placeholder-0c8jt.png",
        calorias: 380,
        tiempo: "25 min",
        picante: 0,
        rating: 4.5,
        ingredientes: ["Pescado fresco", "Hierbas", "Ensalada", "Papas"]
      },
      {
        id: 9,
        nombre: "Parrillada Marina",
        descripcion: "Selección de langostinos, pulpo, calamar y pescado a la parrilla, marinados en especias secretas. Para compartir y disfrutar.",
        precio: 65.00,
        destacado: true,
        imagen: "../public/images/seafood-grill.png",
        calorias: 680,
        tiempo: "40 min",
        picante: 1,
        rating: 4.8,
        ingredientes: ["Langostinos", "Pulpo", "Calamar", "Pescado", "Especias secretas"]
      },
      {
        id: 10,
        nombre: "Sudado de Pescado",
        descripcion: "Pescado fresco cocido al vapor con cebolla, tomate, ají amarillo y culantro. Acompañado de yuca sancochada y frijoles.",
        precio: 38.00,
        destacado: false,
        imagen: "../public/images/sudado-pescado-vapor-yuca-peruano.png",
        calorias: 420,
        tiempo: "30 min",
        picante: 1,
        rating: 4.6,
        ingredientes: ["Pescado", "Cebolla", "Tomate", "Ají amarillo", "Yuca", "Frijoles"]
      },
      {
        id: 11,
        nombre: "Chupe de Camarones",
        descripcion: "Sopa cremosa con camarones frescos, huevo pochado, queso fresco, leche evaporada y arroz. Un abrazo cálido del mar arequipeño.",
        precio: 48.00,
        destacado: true,
        imagen: "../public/images/chupe-camarones-peruano.png",
        calorias: 450,
        tiempo: "35 min",
        picante: 1,
        rating: 4.7,
        ingredientes: ["Camarones", "Huevo", "Queso fresco", "Leche", "Arroz"]
      },
      {
        id: 12,
        nombre: "Lenguado Meunière",
        descripcion: "Filete de lenguado en mantequilla dorada con alcaparras, limón y perejil fresco. Acompañado de puré de papas y vegetales.",
        precio: 52.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 480,
        tiempo: "28 min",
        picante: 0,
        rating: 4.6,
        ingredientes: ["Lenguado", "Mantequilla", "Alcaparras", "Limón", "Puré de papas"]
      }
    ],
    postres: [
      {
        id: 13,
        nombre: "Suspiro Limeño",
        descripcion: "Dulce de leche cremoso coronado con merengue suave y un toque de canela. El postre más romántico del Perú.",
        precio: 18.00,
        destacado: true,
        imagen: "../public/images/suspiro-limeno.png",
        calorias: 320,
        tiempo: "5 min",
        picante: 0,
        rating: 4.8,
        ingredientes: ["Dulce de leche", "Merengue", "Canela", "Vainilla"]
      },
      {
        id: 14,
        nombre: "Mazamorra Morada",
        descripcion: "Postre tradicional de maíz morado con frutas frescas, canela y clavo de olor. Acompañado de arroz con leche.",
        precio: 15.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 280,
        tiempo: "8 min",
        picante: 0,
        rating: 4.4,
        ingredientes: ["Maíz morado", "Frutas", "Canela", "Clavo", "Arroz con leche"]
      },
      {
        id: 15,
        nombre: "Tres Leches",
        descripcion: "Bizcocho esponjoso empapado en tres tipos de leche, coronado con merengue tostado y canela.",
        precio: 20.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 380,
        tiempo: "6 min",
        picante: 0,
        rating: 4.5,
        ingredientes: ["Bizcocho", "Leche evaporada", "Leche condensada", "Crema", "Merengue"]
      },
      {
        id: 16,
        nombre: "Picarones",
        descripcion: "Tradicionales picarones peruanos bañados en miel de chancaca. Crujientes por fuera, suaves por dentro.",
        precio: 16.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 340,
        tiempo: "12 min",
        picante: 0,
        rating: 4.3,
        ingredientes: ["Zapallo", "Camote", "Harina", "Miel de chancaca"]
      }
    ],
    bebidas: [
      {
        id: 17,
        nombre: "Pisco Sour",
        descripcion: "Cóctel bandera del Perú preparado con pisco puro, limón fresco, jarabe de goma, clara de huevo y gotas de amargo de angostura.",
        precio: 25.00,
        destacado: true,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 180,
        tiempo: "3 min",
        picante: 0,
        rating: 4.9,
        ingredientes: ["Pisco", "Limón", "Jarabe de goma", "Clara de huevo", "Amargo"]
      },
      {
        id: 18,
        nombre: "Chicha Morada",
        descripcion: "Bebida refrescante de maíz morado con piña, manzana, canela y clavo de olor. Antioxidante natural.",
        precio: 12.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 120,
        tiempo: "2 min",
        picante: 0,
        rating: 4.6,
        ingredientes: ["Maíz morado", "Piña", "Manzana", "Canela", "Clavo"]
      },
      {
        id: 19,
        nombre: "Inca Kola",
        descripcion: "La gaseosa dorada del Perú, con su sabor único y refrescante que acompaña perfectamente nuestros platos tradicionales.",
        precio: 8.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 140,
        tiempo: "1 min",
        picante: 0,
        rating: 4.2,
        ingredientes: ["Agua carbonatada", "Azúcar", "Saborizantes naturales"]
      },
      {
        id: 20,
        nombre: "Vino Tinto Nacional",
        descripcion: "Copa de vino tinto peruano seleccionado de los mejores viñedos de Ica, con notas frutales.",
        precio: 18.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 125,
        tiempo: "1 min",
        picante: 0,
        rating: 4.4,
        ingredientes: ["Uvas tintas", "Taninos naturales"]
      },
      {
        id: 21,
        nombre: "Agua Mineral",
        descripcion: "Agua mineral natural sin gas o con gas, perfecta para acompañar cualquier comida.",
        precio: 6.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 0,
        tiempo: "1 min",
        picante: 0,
        rating: 4.0,
        ingredientes: ["Agua mineral natural"]
      },
      {
        id: 22,
        nombre: "Jugo Natural",
        descripcion: "Jugos frescos de maracuyá, mango, papaya o naranja. Preparados al momento con frutas de temporada.",
        precio: 10.00,
        destacado: false,
        imagen: "../public/images/placeholder.svg?height=200&width=300",
        calorias: 90,
        tiempo: "3 min",
        picante: 0,
        rating: 4.5,
        ingredientes: ["Frutas frescas", "Agua", "Azúcar natural"]
      }
    ]
  }